sync_time:
  description: Syncronize gateway's time to HA local time.

send_message:
  description: Send an arbitrary (but valid) OpenWebNet message to the gateway.
  fields:
    message:
      description: Valid OpenWebNet message.
      example: "*1*0*0##"

start_sending_instant_power:
  description: Get automatic instant power draw updates for a sensor.
  fields:
    entity_id:
      description: Name(s) of entities that will start sending instant power information.
      example: "sensor.general_power"
    duration:
      description: For how long the instant power information will be sent.
      example: "60"

get_partial_daily_consumption:
  description: Get today's power consumption up to now for a sensor.
  fields:
    entity_id:
      description: Name(s) of entities that will send power consumption information.
      example: "sensor.general_power"

get_hourly_consumption:
  description: Get hourly power consumption for a specific date for a sensor.
  fields:
    entity_id:
      description: Name(s) of entities that will send power consumption information.
      example: "sensor.general_power"
    date:
      description: Date of the hourly power consumption information sent.
      example: "2019-12-30"